slack_uri: https://slack.com
spotify_account_uri: https://accounts.spotify.com
spotify_api_uri: https://api.spotify.com
sign_up_uri: ${SIGN_UP_URI}

secret:
  spotify:
    client_id: ${SPOTIFY_CLIENT_ID}
    client_secret: ${SPOTIFY_CLIENT_SECRET}
  slack:
    client_id: ${SLACK_CLIENT_ID}
    client_secret: ${SLACK_CLIENT_SECRET}
    bot_token: ${SLACK_BOT_TOKEN}

spotmystatus:
  polling_rate: ${SLACK_POLLING_RATE:10000}
  passive_polling_probability: ${PASSIVE_POLLING_PROBABILITY:30}
  passivate_after_min: ${PASSIVATE_AFTER:60}
  passivate_start_hr: ${PASSIVATE_START:21}
  passivate_end_hr: ${PASSIVATE_END:6}
  timeout: ${POLLING_TIMEOUT:2000}

spring:
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog-master.xml
  jpa:
    database: POSTGRESQL
    open-in-view: false
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver