spring:
  thymeleaf:
    cache: false
    enabled: true
    suffix: ".html"
    prefix: "classpath:/static/"

server:
  error:
    whitelabel:
      enabled: false
    path: "/dummy"

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health}