# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Echo build number
        run: echo $GITHUB_RUN_NUMBER "and"  $GITHUB_RUN_ID

# todo cleanup git history
#      - name: Generate deployment package
#        run: zip -r deploy-3.zip * -x ./build/libs/spotmystatus-0.0.1-SNAPSHOT.jar
#      - name: Deploy to AWS Beanstalk
#        uses: einaregilsson/beanstalk-deploy@v13
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: SpotMyStatus
#          environment_name: Spotmystatus-env-1
#          version_label: Ver-3
#          use_existing_version_if_available: true
#          region: eu-central-1
#          deployment_package: deploy-3.zip
